py-3.x compat: don't pretend Target is a value
Target implementation formally satisfies python2's requirements for
dict keys, but python3 wants __hash__.  looking at the code it's clear
that the implementation is dangerously wrong (any two Target instances
representing the same systemtype (sles12-x86_64, say) are regarded as
equal!  i'll drop the __eq__, __ne__, etc.  methods once i'm reasonably
confident nothing depends on them (anymore).

meanwhile, in python-3.4...

TypeError: unhashable type: 'Target'

mtui> list_packages
error: s390vsl048.suse.de: failed to run command "rpm -q zeromq-devel libzmq3"
error: Traceback (most recent call last):
  File "/home/roman/wc/MINE/mtui/mtui/prompt.py", line 197, in cmdloop
    cmd.Cmd.cmdloop(self)
  File "/usr/lib/python3.4/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/roman/wc/MINE/mtui/mtui/prompt.py", line 229, in onecmd
    self.config, self.sys, self.log, self
  File "/home/roman/wc/MINE/mtui/mtui/commands.py", line 225, in run
    for target, pvs in hosts.query_versions(pkgs).items():
  File "/home/roman/wc/MINE/mtui/mtui/target/__init__.py", line 109, in query_versions
    rs[x] = x.query_package_versions(packages)
TypeError: unhashable type: 'Target'